# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('activity_type', models.PositiveSmallIntegerField(choices=[(1, 'Talk'), (2, 'Light talk'), (3, 'Workshop'), (4, 'Keynote')])),
                ('description', models.TextField()),
                ('motivation', models.TextField()),
                ('requirements', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('cellphone', models.CharField(blank=True, max_length=20)),
                ('biography', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call_for_applications.Speaker'),
        ),
    ]
